#!/usr/bin/env bash
# Regenerates src/cloudflared_pins.rs for the latest cloudflared release.
set -euo pipefail
cd "$(dirname "$0")/.."

VERSION=$(curl -fsSL https://api.github.com/repos/cloudflare/cloudflared/releases/latest \
  | grep -oP '"tag_name":\s*"\K[^"]+')
echo "Pinning cloudflared $VERSION"

ARTIFACTS=(
  "linux-amd64 cloudflared-linux-amd64"
  "linux-arm64 cloudflared-linux-arm64"
  "darwin-amd64 cloudflared-darwin-amd64.tgz"
  "darwin-arm64 cloudflared-darwin-arm64.tgz"
  "windows-amd64 cloudflared-windows-amd64.exe"
)

{
  echo "// Generated by scripts/pin-cloudflared.sh — do not edit by hand."
  echo "pub const CLOUDFLARED_VERSION: &str = \"$VERSION\";"
  echo "pub const PINS: &[(&str, &str, &str)] = &["
  for entry in "${ARTIFACTS[@]}"; do
    key="${entry%% *}"; file="${entry#* }"
    url="https://github.com/cloudflare/cloudflared/releases/download/$VERSION/$file"
    sum=$(curl -fsSL "$url" | sha256sum | cut -d' ' -f1)
    echo "    (\"$key\", \"$file\", \"$sum\"),"
  done
  echo "];"
} > src/cloudflared_pins.rs
echo "Wrote src/cloudflared_pins.rs"
