// Generated by scripts/pin-cloudflared.sh — do not edit by hand.
pub const CLOUDFLARED_VERSION: &str = "2026.7.2";
pub const PINS: &[(&str, &str, &str)] = &[
    (
        "linux-amd64",
        "cloudflared-linux-amd64",
        "ec905ea7b7e327ff8abdde8cb64697a2152de74dbcdbf6aec9db8364eb3886cd",
    ),
    (
        "linux-arm64",
        "cloudflared-linux-arm64",
        "405df476437e027fc6d18729a5a77155c0a33a6082aeee60a799a688f3052e66",
    ),
    (
        "darwin-amd64",
        "cloudflared-darwin-amd64.tgz",
        "4ee0d3b48a990a2f9b5faec5838f73ec1f400aa8e0a4864be576adfafec406cb",
    ),
    (
        "darwin-arm64",
        "cloudflared-darwin-arm64.tgz",
        "2086e51c61d6565781d84117a5007d0c826d03ffdc74acb91c08c167f9f8cd7c",
    ),
    (
        "windows-amd64",
        "cloudflared-windows-amd64.exe",
        "cdb5d4432f6ae1595654a692a51308b69d2bf7af961f5578d9391837cf072df9",
    ),
];
